### PR TITLE
tutor-or-student

### PR DESCRIPTION
**Pull request by cmhughes**
Hi Robert,
I thought I'd add this to the queue, no rush to review it :)

This pull request features implementation of:
    - tutoronly and studentonly commands
    - tutor and student environments
    - tutororstudent command (two arguments)
Each of the above is dependent upon specsolns option being active or not.

If my other pull requests are merged, this one may not merge cleanly -- if so, I'll happily clean it up. 

As always, any/all feedback welcome.
Best
Chris

### CODE REVIEW

**Comment by rbrignall** [comment]
Hi Chris,

Basically I'm happy with this, thanks! However, a few minor things:
1) It doesn't want to merge cleanly, but it's only the two pdf files that are causing trouble (maybe you can rectify this easily? If needs be just get rid of them from the merge and we can replace them afterwards.)

2) I suggest this gets outn version number 0.7, as it's a semi-significant release.

3) Not sure about "For tutors only" and "For students only"... Perhaps the thing to do is have a \@tutoronlytitle and \@studentonlytitle which stores these, and then \tutoronlytitle{blah} will replace whatever it contains, etc. Similarly with the blue colour: this is probably fine, but someone will want something else, so we might want to allow, e.g. \begin{tutor}[red] ... to specify alternative colours. 

Cheers,

Robert

**Comment by cmhughes** [comment]
Hi Robert,
Many thanks indeed for the feedback; I'll be very happy to incorporate all
of this, hopefully by early next week. I'll let you know when I've updated
it.

Thanks again
Chris

**Comment by cmhughes** [comment]
Hi Robert,
Thanks again for the feedback.

I've implemented `tutoronlytitle` and `studentonlytitle` which hook into, respectively, `@tutoronlytitle` and `@studentonlytitle` as requested. I've updated the documentation to detail these two optional commands; I've also updated the version number.

The colour choices were hard-coded into `tntemplate.tex` and the option remains for users to redefine `tutor` and `student` environments as they see fit in their own preamble. 

I hope this sounds ok -- as ever, do let me know if you'd like it done differently.
Best
Chris

PS: for reference, this pull request is related to https://github.com/rbrignall/OU-SUPPS/issues/13

**Review by rbrignall — CHANGES_REQUESTED** [review]
Hi,

Thanks for this. One question: do `\tutoronlytitle` and `\studentonlytitle` need to be in the preamble? It's a natural place for them, but in theory they could go anywhere, I think, so perhaps in the documentation they are as well to go in the same place as `\studentonly`, etc?

Related to this: In the template tex, perhaps add a comment where `\tutoronlytitle` and `\studentonlytitle` are inserted to clarify what they do (just in case someone thinks it sets the title of the whole document...!).

R

**Comment by cmhughes** [comment]
Hi Robert,
Thanks for the follow-ups; I've moved the documentation of the `tutoronlytitle` and `studentonlytitle` commands to be after the `tutor` and `student` environments respectively.

I have also commented out `\tutoronlytitle` and `\studentonlytitle` in `tntemplate.tex` and have commented them for reference.

I see that there are 'Changes requested' here on github, but it says: *1 review requesting changes by reviewers with write access* so I am unable to see them....? 

Thanks again -- very happy to make other changes, as you see fit.
Best
Chris

**Review by rbrignall — APPROVED** [review]

**Comment by rbrignall** [comment]
Thanks, all looks good. Yeah, I don't really know what I'm doing here, can you tell? Anyway, I'll merge all this stuff now -- thanks!

**Pull request merged**
