### PR TITLE
Feature/horizontal lines subtotal total

### PR DESCRIPTION
**Pull request by cmhughes**
Hi Robert,
This branch implements the ability to draw horizontal rules after `\total`, `\total*`, `\subtotal` and `\subtotal*` commands. 

By default, the lines are drawn, and are done so in `black`, horizontally offset by `.1\textwidth`, with a width of `1.5\textwidth` and a height of `2pt` for `total` and `1pt` for `subtotal`. Every aspect of both of these lines (including turning them on/off) is customisable with a `key=value` approach -- I've provided details in `Documentation/ou-supps.tex` and `Documentation/ou-supps.pdf`.

I hope it looks ok, and am very open to any feedback that you may have.
Best
Chris

### CODE REVIEW

**Comment by rbrignall** [comment]
Looks good, and nice idea to use pgfkeys -- a useful approach that we should consider more generally for customisations.

**Comment by cmhughes** [comment]
Cool, thanks!

Yes, I was thinking about creating a shortcut key value approach for
document meta data, such as author, date, faculty, module, etc.

**Comment by rbrignall** [comment]
That would be a fun feature -- I wonder how many people would prefer this method, or switch to it? One to think about for a while, maybe.

**Comment by cmhughes** [comment]
Yes, I agree; I'll see if I can put something together and show you the
mark up. Importantly, it wouldn't replace the current setup, just provide
an alternative.

**Pull request merged**
